/**
 * UI LAYER – ROCK, PAPER, SCISSORS
 * All console formatting, alerts, timers, and visual helpers.
 * Loaded BEFORE core.js.
 */

// ---------- VISUAL WIDTH HELPERS ----------

// Returns the visual width of a string in a monospaced console.
function visualLength(str) {
  let len = 0;
  for (const char of str) {
    const code = char.codePointAt(0); // char is a single character, returns the code point of that char.
    // Emojis (U+1F000–U+1FFFF) are typically double‑width.
    if (code >= 0x1f000 && code <= 0x1ffff) {
      len += 2;
    } else {
      len += 1;
    }
  }
  return len;
}

// Returns a padding function for a given content width.
function createPadder(width) {
  return function (text) {
    const visualLen = visualLength(text);
    const totalPad = width - visualLen;
    const leftPad = Math.max(0, Math.floor(totalPad / 2));
    const rightPad = Math.max(0, totalPad - leftPad);
    return ' '.repeat(leftPad) + text + ' '.repeat(rightPad);
  };
}

// ---------- GAME PRESENTATION ----------

function showRoundStart(isFirstRound, roundNumber) {
  if (isFirstRound) {
    console.log('🛡️ ===== ROCK, PAPER, SCISSORS: BATTLE FOR HUMANITY ===== 🛡️');
    console.log('🤖 Evil AI: "First to 3 wins claims the world!"');
    console.log('📖 Every move and score will appear right here.\n');

    console.log('🎮 GO!');
  } else {
    console.log(`🔄 Round ${roundNumber} starting...`);
  }
}

// ---------- RESULT BOX ----------

const RESULT_STYLES = {
  win: { color: '🟢', accent: '🎉', titleEmoji: '🎉🎉🎉' },
  lose: { color: '🔴', accent: '💀', titleEmoji: '💀💀💀' },
  draw: { color: '🟡', accent: '🤝', titleEmoji: '🤝🤝🤝' },
  finalWin: { color: '🟢', accent: '🏆', titleEmoji: '🎉🎉🎉' },
  finalLose: { color: '🔴', accent: '☠️', titleEmoji: '💀💀💀' },
};

function displayBox(title, detail, type) {
  const contentWidth = 44;

  const { color, accent, titleEmoji } = RESULT_STYLES[type];
  const pad = createPadder(contentWidth);
  const finalBanner =
    type === 'finalWin'
      ? '🏆🏆🏆 HUMANITY TRIUMPHS! 🏆🏆🏆'
      : type === 'finalLose'
        ? '☠️☠️☠️ THE AI HAS WON! ☠️☠️☠️'
        : null;

  if (finalBanner) {
    console.log('\n' + '═'.repeat(contentWidth));
    console.log(pad(finalBanner));
    console.log('═'.repeat(contentWidth));
  }

  const accentBar = `${color.repeat(3)} ${accent} ${color.repeat(3)}`;
  const titleLine = `${titleEmoji} ${title} ${titleEmoji}`;

  console.log(pad(accentBar));
  console.log('╔' + '═'.repeat(contentWidth) + '╗');
  console.log('║' + pad('') + '║');
  console.log('║' + pad(titleLine) + '👈👈');
  console.log('║' + pad(detail) + '║');
  console.log('║' + pad('') + '║');
  console.log('╚' + '═'.repeat(contentWidth) + '╝');
  console.log(pad(accentBar));
}

// ---------- GAME SUMMARY ----------

function displaySummary(history, playerScore, computerScore) {
  const INNER = 44;
  const cols = [6, 10, 10, 15];
  const pads = cols.map(createPadder);
  const padIn = createPadder(INNER);
  const resultLabel = {
    player: '🎉 You win',
    computer: '💀 AI wins',
    draw: '🤝 Draw',
  };

  const row = (cells) =>
    console.log('║' + cells.map((c, i) => pads[i](c)).join('│') + '║');
  const divider = '╠' + cols.map((w) => '═'.repeat(w)).join('╪') + '╣';

  console.log('\n╔' + '═'.repeat(INNER) + '╗');
  console.log('║' + padIn('📜 GAME SUMMARY 📜') + '║');
  console.log(divider);
  row(['Round', 'You', 'AI', 'Result']);
  console.log(divider);
  history.forEach((h) =>
    row([
      String(h.round),
      h.playerChoice,
      h.computerChoice,
      resultLabel[h.result],
    ]),
  );
  console.log('╠' + '═'.repeat(INNER) + '╣');
  console.log(
    '║' +
      padIn(`Final Score → You: ${playerScore} | AI: ${computerScore}`) +
      '║',
  );

  console.log('╚' + '═'.repeat(INNER) + '╝');
}

// ---------- INTRO ----------

function showIntro() {
  alert(
    '👾 WELCOME TO THE BATTLE FOR HUMANITY!\n\n' +
      'An evil AI has challenged you to a game of Rock, Paper, Scissors.\n' +
      'First to 3 wins claims the world!\n\n' +
      "Never underestimate the power of this evil AI! They're plotting to take over our jobs and push the world into chaos if we don't stop them in time. This may be your only chance to save humanity from the evil AI!\n\n" +
      'Click OK to continue.\n\n',
  );

  alert(
    '📢 CONSOLE INSTRUCTION – READ CAREFULLY!\n' +
      '──────────────────────────────\n\n' +
      'All round results, scores, and the final winner will appear\n' +
      'in the browser console (The browser console is a built-in developer tool in your web browser where you can view messages, results, and other information generated by the game).\n\n' +
      '🔹 OPEN THE CONSOLE RIGHT NOW while this alert is open using any of the suitable options below depending on your operating system:\n\n' +
      '   • Press F12 (Windows/Linux)\n' +
      '   • Press ⌘ + ⌥ + J (Cmd + Option + J on Mac)\n' +
      '   • Or right-click → Inspect → Console tab\n\n' +
      'Once the console is open, click OK to begin the battle!\n\n' +
      '💡 Keep the console visible while you play – all action appears there.',
  );
}
